#!/usr/bin/env python3
"""Generate 500 diverse calibration prompts for PHANTOM CORE."""
import json, os

prompts = [
    # CODE (100)
    "Write a Python function that implements quicksort algorithm with detailed comments.",
    "Implement a binary search tree in C++ with insert, delete, and search operations.",
    "Write a Rust function that safely parses a JSON string into a HashMap.",
    "Create a JavaScript class for a doubly-linked list with reversal.",
    "Explain the difference between TCP and UDP protocols with code examples.",
    "How does garbage collection work in Java? Explain generational GC.",
    "Write a Python decorator that implements memoization with an LRU cache.",
    "Implement the A* pathfinding algorithm in Python with a grid-based example.",
    "Write a CUDA kernel for matrix multiplication with shared memory optimization.",
    "Create a Go program that implements a concurrent web scraper.",
    "Explain memory-mapped I/O and write C code demonstrating its use.",
    "Implement a simple HTTP server in Python without any web framework.",
    "Write a TypeScript function that deeply clones an object with circular references.",
    "Create a Redis-like in-memory key-value store in C with TTL support.",
    "Implement a thread pool in Java with work-stealing capabilities.",
    "Write a Python script that monitors file system changes in real-time.",
    "Create a simple compiler frontend for arithmetic expressions in Python.",
    "Implement consistent hashing in Go for distributed systems.",
    "Write a WebSocket server in Node.js that broadcasts messages.",
    "Create a lock-free queue in C++ using atomic operations.",
    "Implement the Raft consensus algorithm state machine in pseudocode.",
    "Write a Python function to serialize and deserialize a binary tree.",
    "Create a mini version control system in Python that supports commit and diff.",
    "Implement a bloom filter in Rust with configurable false positive rate.",
    "Write a SQL query to find employees with salaries above department average.",
    "Create a simple neural network from scratch in Python without frameworks.",
    "Implement a rate limiter using the token bucket algorithm in Go.",
    "Write a Python script that generates and solves a maze using DFS.",
    "Create a simple filesystem in C using FUSE.",
    "Implement the observer design pattern in Java with a practical example.",
    "Write a bash script that sets up a complete development environment.",
    "Create a Python function that finds the longest common subsequence.",
    "Implement a priority queue using a Fibonacci heap in C++.",
    "Write a Rust program that safely handles multiple error types.",
    "Create a simple task scheduler in Python with dependencies.",
    "Implement a trie data structure in JavaScript for autocomplete.",
    "Write a Python script that generates API documentation from docstrings.",
    "Create a simple database query optimizer in Python.",
    "Implement the Dijkstra shortest path algorithm with a priority queue.",
    "Write a C program that implements a memory allocator.",
    "Create a Python class that implements lazy evaluation.",
    "Implement a simple regex engine in Python supporting ., *, and [].",
    "Write a Go function that performs parallel merge sort.",
    "Create a simple load balancer in Python with round-robin.",
    "Implement the PageRank algorithm in Python for a directed graph.",
    "Write a Python script that converts between image formats.",
    "Create a simple pub/sub messaging system in Python using asyncio.",
    "Implement a skip list in C with O(log n) search time.",
    "Write a Python decorator that adds retry logic with backoff.",
    "Create a simple ORM in Python that maps objects to SQLite tables.",
    "Implement the Knuth-Morris-Pratt string matching algorithm.",
    "Write a Python generator that reads large files without loading all into memory.",
    "Create a command-line calculator in Rust with variables and functions.",
    "Implement a simple event sourcing system in Python.",
    "Write a Python script that analyzes git log and generates statistics.",
    "Create a simple DNS resolver in Python using raw UDP sockets.",
    "Implement the producer-consumer pattern in Java using BlockingQueue.",
    "Write a Python function that validates complex nested JSON schema.",
    "Create a CI/CD pipeline configuration parser in Python.",
    "Implement a B-tree in C for database indexing.",
    "Write a Python script for basic sentiment analysis using NLP.",
    "Create a simple reverse proxy in Go with health checks.",
    "Implement an LRU cache with O(1) get and put operations.",
    "Write a Python context manager for database transactions with rollback.",
    "Create a compression algorithm in Python similar to LZ77.",
    "Implement the Bellman-Ford algorithm for negative weights.",
    "Write a Python script that generates random test data.",
    "Create a microservice framework in Python with service discovery.",
    "Implement a circular buffer in C with thread-safe operations.",
    "Write a Python function to convert infix to postfix notation.",
    "Create a simple graph database in Python.",
    "Implement a simple garbage collector using mark-and-sweep in C.",
    "Write a Python script that benchmarks sorting algorithms.",
    "Create a template engine in Python with loops and conditionals.",
    "Implement the Floyd-Warshall all-pairs shortest paths algorithm.",
    "Write a Rust program that processes CSV files in parallel.",
    "Create a Python disjoint set with path compression and union by rank.",
    "Implement a packet sniffer in Python using raw sockets.",
    "Write a JavaScript debounce and throttle implementation.",
    "Create a simple blockchain in Python with proof-of-work.",
    "Implement topological sort using DFS in Python.",
    "Write a C++ template class for a generic graph with BFS and DFS.",
    "Create a Python script for Fibonacci via matrix exponentiation.",
    "Implement a simple HTTP/2 frame parser in Rust.",
    "Write a Python function that finds all anagram groups.",
    "Create a simple message queue in Go with disk persistence.",
    "Implement the Sieve of Eratosthenes efficiently.",
    "Write a Python script that monitors system resources.",
    "Create a simple virtual machine in C for bytecode.",
    "Implement a red-black tree in Java with rotations.",
    "Write a Python function for matrix operations without numpy.",
    "Create a service mesh in Go with circuit breaker pattern.",
    "Implement a diff algorithm similar to unified diff.",
    "Write a C program for inter-process communication with pipes.",
    "Create a Python class implementing the strategy pattern.",
    "Implement a search engine with inverted index in Python.",
    "Write a Rust function with async I/O using tokio.",
    "Create a Python number base conversion script.",
    "Implement the Hungarian algorithm for assignment problems.",
    "Write a Go key-value store with write-ahead logging.",
    # MATH (100)
    "Prove that the square root of 2 is irrational.",
    "Solve: 3x + 2y - z = 1, 2x - 2y + 4z = -2, -x + y/2 - z = 0.",
    "Explain Bayes theorem with three real-world examples.",
    "What is the Riemann hypothesis and why does it matter?",
    "Derive the formula for the sum of an arithmetic series.",
    "How do you calculate eigenvalues of a 3x3 matrix?",
    "Explain gradient descent and backpropagation with mathematics.",
    "What is a Fourier transform? Derive it from the Fourier series.",
    "Prove there are infinitely many prime numbers.",
    "Explain the central limit theorem and its significance.",
    "What is the Monty Hall problem? Prove the optimal strategy.",
    "Derive the quadratic formula by completing the square.",
    "Explain Markov chains with a stationary distribution example.",
    "What is the P vs NP problem? Explain its significance.",
    "Calculate the determinant of a 4x4 matrix.",
    "Explain the birthday paradox for 23 people.",
    "What is the fundamental theorem of calculus? Prove it.",
    "Derive the Taylor series for e^x, sin(x), and cos(x).",
    "Explain the pigeonhole principle with CS applications.",
    "What is the Halting Problem? Prove it is undecidable.",
    "Calculate expected value and variance of binomial distribution.",
    "Explain graph coloring and the four color theorem.",
    "What is the Euler-Lagrange equation?",
    "Prove every continuous function on [a,b] attains its maximum.",
    "Explain convergent vs divergent series with examples.",
    "What is the Chinese Remainder Theorem? Solve a system.",
    "Derive the volume formula for an n-dimensional sphere.",
    "Explain entropy in information theory.",
    "What is the Cauchy-Schwarz inequality? Prove it.",
    "Calculate the probability of winning at craps first roll.",
    "Explain the simplex algorithm for linear programming.",
    "What is the spectral theorem for symmetric matrices?",
    "Derive Stirling's approximation for n factorial.",
    "Explain PCA from a linear algebra perspective.",
    "What is the Jacobian matrix and how is it used?",
    "Prove the binomial theorem using mathematical induction.",
    "Explain the Gram-Schmidt orthogonalization process.",
    "What is the law of large numbers? Both versions.",
    "Calculate integral of sin^2(x)*cos^3(x) from 0 to pi.",
    "Explain topological sorting with proof of correctness.",
    "What is the Banach fixed-point theorem?",
    "Derive the compound interest formula with continuous compounding.",
    "Explain dual spaces in linear algebra.",
    "What is the master theorem for recurrence relations?",
    "Calculate ways to tile a 2xn rectangle with dominoes.",
    "Explain permutations vs combinations with examples.",
    "What is the Jordan normal form? When does it exist?",
    "Derive the 3D rotation matrix using Euler angles.",
    "Explain NP-completeness with examples.",
    "What is the Gauss-Bonnet theorem?",
    "Trains at 120 and 80 km/h from 500 km apart. When do they meet?",
    "Ball dropped from 100m, 60% bounce. Total distance traveled?",
    "How many ways to place 8 non-attacking rooks on a chessboard?",
    "Expected coin flips to get 3 heads in a row?",
    "Find all solutions to x^3 - 6x^2 + 11x - 6 = 0.",
    "Surface area of a torus with radii R and r.",
    "What is the two-envelope problem optimal strategy?",
    "Prove the set of rational numbers is countable.",
    "How many different Sudoku puzzles exist?",
    "What is the Collatz conjecture? Verify for first 100 numbers.",
    "Fibonacci sequence modulo 10: find the period.",
    "Explain generating functions in combinatorics.",
    "TSP: explain approximation algorithms.",
    "Derive distance formula in n-dimensional space.",
    "Explain mathematical groups with examples.",
    "What is the max-flow min-cut theorem?",
    "Binary strings of length n with no consecutive 1s: how many?",
    "Explain measure theory in probability.",
    "What is Godel's incompleteness theorem?",
    "Derive the sum of squares formula.",
    "Explain RSA cryptosystem mathematically.",
    "What is the Lagrange multiplier method?",
    "Area under parametric curve x=cos(t), y=sin(t).",
    "L1 vs L2 regularization: mathematical comparison.",
    "What is the coupon collector problem?",
    "Prove unique prime factorization of every positive integer.",
    "Explain homomorphisms in abstract algebra.",
    "What is the Perron-Frobenius theorem?",
    "Calculate the nth Catalan number recursively.",
    "Explain convexity in optimization.",
    "What is the Nyquist-Shannon sampling theorem?",
    "Derive the area formula for an ellipse.",
    "Explain Monte Carlo methods for integration.",
    "Metric space vs topological space differences.",
    "Probability of a full house in poker.",
    "Explain tensor products in linear algebra.",
    "What is the Stone-Weierstrass theorem?",
    "Derive the heat equation from physics.",
    "Explain numerical stability in algorithms.",
    "What is the Lovász Local Lemma?",
    "Determinant of a Vandermonde matrix.",
    "Relationship between eigenvalues and singular values.",
    "What is Ramsey theory? R(3,3) example.",
    "Derive the wave equation from physics.",
    "Well-ordering and its relation to induction.",
    "Spectral gap of a graph: why does it matter?",
    "Expected fixed points in a random permutation.",
    "Explain compactness in topology.",
    "What is the minimax theorem in game theory?",
    "Derive the binomial distribution from first principles.",
    "Differential equations and dynamical systems connection.",
    # SCIENCE (100)
    "What caused World War I? Main contributing factors.",
    "Explain DNA structure and genetic information encoding.",
    "How does the immune system respond to a viral infection?",
    "Describe photosynthesis at the molecular level.",
    "What are black holes and how do we detect them?",
    "Explain quantum entanglement and the EPR paradox.",
    "How does CRISPR-Cas9 gene editing work?",
    "Describe the theory of comparative advantage.",
    "What is general relativity? Explain spacetime curvature.",
    "How do vaccines work? mRNA vs traditional.",
    "Describe plate tectonics and geological activity.",
    "What is dark matter? What evidence supports it?",
    "Explain antibiotic resistance in bacteria.",
    "How does nuclear fusion work in the Sun?",
    "What is the microbiome's effect on health?",
    "History of the Internet from ARPANET to today.",
    "How does a transistor work at quantum level?",
    "What are prions and how do they cause disease?",
    "Explain the greenhouse effect with evidence.",
    "How does the brain process visual information?",
    "What is epigenetics? Environmental effects on genes.",
    "Describe the Standard Model of particle physics.",
    "How do lithium-ion batteries work?",
    "What are gravitational waves? How were they detected?",
    "Explain the nitrogen cycle in ecosystems.",
    "How does an MRI scanner work?",
    "What is the multiverse hypothesis?",
    "Describe evolution by natural selection.",
    "How does the ocean conveyor belt affect climate?",
    "What are stem cells and their medical importance?",
    "Explain semiconductor physics and p-n junctions.",
    "How does the ozone layer protect Earth?",
    "What is neuroplasticity?",
    "Describe drug-receptor protein interactions.",
    "How does radar and the Doppler effect work?",
    "What is the evidence for the Big Bang?",
    "Explain protein folding and misfolding diseases.",
    "How do fiber optic cables transmit data?",
    "What has the Large Hadron Collider discovered?",
    "Describe the water cycle and climate disruption.",
    "How does gene therapy work? Examples.",
    "What is quantum computing vs classical?",
    "Explain carbon dating and its limitations.",
    "How does the human heart pump blood?",
    "What are metamaterials?",
    "Describe RNA types and their functions.",
    "How does GPS work? Role of relativity.",
    "What is the Drake equation?",
    "Explain ocean acidification chemistry.",
    "How do electric motors work?",
    "What is the Cambrian explosion?",
    "Describe nuclear fission and power plants.",
    "How does the endocrine system regulate hormones?",
    "What are supernovae and element creation?",
    "Explain solar panel photovoltaic physics.",
    "How does the placebo effect work neurologically?",
    "What is the Hubble constant?",
    "How are earthquakes measured and predicted?",
    "Explain mRNA translation at the ribosome.",
    "What is the Anthropocene?",
    "Explain superconductivity and applications.",
    "How does immune checkpoint therapy work for cancer?",
    "How do we detect exoplanets? Transit method.",
    "Describe the Sun's structure and solar wind.",
    "How does anesthesia work at the cellular level?",
    "What is cosmic inflation theory?",
    "Explain catalytic converters.",
    "How do MRI contrast agents work?",
    "Evidence for continental drift.",
    "Describe speciation and new species emergence.",
    "How does a laser work? Stimulated emission.",
    "What is the Human Genome Project?",
    "Physics of sound and hearing.",
    "How do coral reefs form?",
    "Connection between inflammation and chronic disease.",
    "Chemistry of cooking: what happens when you sear meat?",
    "Artificial photosynthesis research.",
    "What is the gut-brain axis?",
    "Physics of lightning formation.",
    "How do viruses mutate?",
    "Role of telomeres in aging.",
    "Physics of aerodynamic lift.",
    "How does circadian rhythm work molecularly?",
    "What are rare earth elements?",
    "Chemistry of fermentation in winemaking.",
    "How do autonomous vehicles navigate?",
    "What is synthetic biology?",
    "Physics of NMR spectroscopy.",
    "How does the lymphatic system work?",
    "Evidence for life on Mars from rovers.",
    "How are semiconductors fabricated at nanoscale?",
    "How does optogenetics control neurons?",
    "What is dark energy?",
    "Biochemistry of muscle contraction.",
    "Carbon nanotube properties.",
    "Gut microbiome and immune function.",
    "Physics of waves: interference, diffraction, polarization.",
    "CRISPR base editing vs standard CRISPR.",
    "Significance of the cosmic microwave background.",
    "Battery technologies beyond lithium-ion.",
    # CONVERSATIONAL (100)
    "Key skills for a machine learning engineering career.",
    "How to learn a new programming language efficiently.",
    "Pros and cons of remote work vs office work.",
    "6-month study plan for learning machine learning from scratch.",
    "Best books for cognitive science beginners.",
    "How to improve public speaking skills.",
    "Best approach to debugging distributed systems.",
    "How to structure a senior engineering resume.",
    "Key principles of tech team management.",
    "How to transition from SWE to ML.",
    "Startups vs large companies: what to consider.",
    "How to prepare for system design interviews.",
    "Best practices for code review in large teams.",
    "How to manage technical debt effectively.",
    "Most effective way to learn math for CS.",
    "How to build a strong GitHub portfolio.",
    "Key considerations for database schema design.",
    "How to optimize web application performance.",
    "Best strategies for learning and retaining information.",
    "Improving problem-solving for competitive programming.",
    "Ethical considerations in AI development.",
    "How to plan SWE career progression.",
    "Best practices for technical documentation.",
    "How to evaluate new technology adoption.",
    "Learning cloud architecture: AWS/GCP/Azure.",
    "Handling technical disagreements with colleagues.",
    "Software architecture for scalable systems.",
    "Staying current with changing technology.",
    "Time management strategies for developers.",
    "Writing unit tests for complex business logic.",
    "How to mentor junior developers effectively.",
    "Balancing features vs technical improvements.",
    "Migrating monolith to microservices: key considerations.",
    "Learning DevOps and infrastructure automation.",
    "Best practices for API design and versioning.",
    "Improving understanding of computer networking.",
    "Security best practices in software development.",
    "Handling burnout and work-life balance in tech.",
    "Choosing between frontend frameworks.",
    "Communicating tech concepts to non-technical people.",
    "Best resources for learning system design at scale.",
    "Contributing to open source for the first time.",
    "Common mistakes in microservice architecture.",
    "SQL vs NoSQL: how to choose.",
    "Learning operating systems internals effectively.",
    "Setting up CI/CD for a new team.",
    "Key principles of data-driven decision making.",
    "Building expertise in low-level systems programming.",
    "Best practices for configuration management.",
    "Learning Kubernetes and container orchestration.",
    "Key considerations for building real-time systems.",
    "Evaluating third-party libraries and dependencies.",
    "Testing distributed systems effectively.",
    "Handling legacy code when adding features.",
    "Best practices for logging and observability.",
    "Improving understanding of compiler design.",
    "Key principles of event-driven architecture.",
    "Capacity planning for a growing service.",
    "Reducing latency in web applications.",
    "Using design patterns without over-engineering.",
    "Learning cryptography and security effectively.",
    "Building a personal brand in tech.",
    "Key considerations for mobile app development.",
    "Improving project timeline estimation.",
    "Best practices for data pipeline architecture.",
    "Learning ML infrastructure effectively.",
    "Debugging memory leaks in production.",
    "Building resilient systems for failure handling.",
    "Principles of clean code and craftsmanship.",
    "Learning GPU programming and CUDA.",
    "Salary negotiation strategies in tech.",
    "Building effective automated testing pipelines.",
    "Learning functional programming effectively.",
    "Handling data privacy: GDPR and CCPA.",
    "Building multi-tenant SaaS applications.",
    "Learning distributed consensus algorithms.",
    "Git best practices for large teams.",
    "Building a startup as a technical founder.",
    "Learning computer graphics and rendering.",
    "Improving algorithmic thinking for daily engineering.",
    "Principles of site reliability engineering.",
    "Learning embedded systems programming.",
    "Managing geographically distributed teams.",
    "Evaluating ROI of new development tools.",
    "Building recommendation systems.",
    "Architectural decision records: best practices.",
    "Data warehousing and analytics considerations.",
    "Building NLP expertise.",
    "Incident response and postmortem best practices.",
    "Building internal developer platforms.",
    "Learning blockchain technology effectively.",
    "Building accessible web applications (WCAG).",
    "Principles of chaos engineering.",
    "Cloud provider migration strategies.",
    "Building high-performance APIs.",
    "Network security and encryption understanding.",
    "Feature flagging and rollout strategies.",
    "Building search for large datasets.",
    "Edge computing and IoT architecture.",
    "Building effective data visualization dashboards.",
    # CREATIVE (50)
    "Write a short story about an astronaut discovering life on Europa.",
    "Compose a poem about AI and consciousness.",
    "Write a news article from 2150 about climate change.",
    "Dialogue between a philosopher and an AI about free will.",
    "Story about a world where memory is transferable.",
    "Monologue from the last human librarian.",
    "A fairy tale about a robot that learns to dream.",
    "Political speech about space colonization.",
    "Detective story set on a Mars orbital station.",
    "Letter from a time traveler to their past self.",
    "Story about emotions traded as currency.",
    "Myth about how artificial intelligence was born.",
    "Screenplay scene about first contact with aliens.",
    "Haiku series about the seasons of a dying star.",
    "Story about the day the Internet disappears.",
    "Journal entry from the first Moon resident.",
    "Bedtime story about quantum physics for children.",
    "Epic poem about a civilization's rise and fall.",
    "Story about two AIs falling in love.",
    "Restaurant review from the year 3000.",
    "Story about a musician who hears math as music.",
    "Nature documentary narration about urban wildlife.",
    "Story about an archaeologist finding a future computer.",
    "Conversation between the Sun and Moon about humanity.",
    "Story about a programmer who accidentally creates consciousness.",
    "Love letter between entangled quantum particles.",
    "Story where every lie becomes physically visible.",
    "TED talk on simulation theory.",
    "Story about a translator who speaks plant language.",
    "War correspondent report from AI conflict.",
    "Story about a child who sees the future in paintings.",
    "Nobel Prize acceptance speech for AI Ethics.",
    "Story: crew discovers Earth is a simulation.",
    "Meditation guide written by an ancient AI sage.",
    "Story about communally shared dreams.",
    "Recipe for disaster in cooking show style.",
    "Story about a librarian who discovers books are alive.",
    "Diplomatic treaty between humans and AIs.",
    "Story about a painter who paints functional machines.",
    "Survival guide for post-singularity world.",
    "Story about an elevator between parallel universes.",
    "Eulogy for the last internal combustion engine.",
    "Story: mathematician proves reality is a fractal.",
    "Manual for a consciousness transfer machine.",
    "Story about a chef who can taste emotions.",
    "Graduation speech for first AI student class.",
    "Story about music with physical effects.",
    "Travel guide for touring Jupiter's moons.",
    "Story about a philosopher who wakes up as an AI.",
    "Children's book about how computers think.",
]

out = os.path.join("calibration", "datasets")
os.makedirs(out, exist_ok=True)
with open(os.path.join(out, "calibration_prompts.jsonl"), "w", encoding="utf-8") as f:
    for p in prompts:
        json.dump({"text": p}, f, ensure_ascii=False)
        f.write("\n")
print(f"Generated {len(prompts)} calibration prompts.")
